### ISSUE TITLE
Store account information

### ISSUE THREAD

**Issue by Adurol** [DylanVanAssche/harbour-sailbook#16]
I would like to see an option of Sailbook to safe my account information (like web browsers do). That way I wouldn't have to enter my mail address and password all the time on startup of Sailbook.

Not the embedded web browser should store it (I would like it to "reset" on every start --> no cookies, ...) but saved by Sailbook itself. It would then autofill on the landing page and I would only have to click on login 😏

I'm not sure how hard it is, but if the credentials could be stored on the phone in a more secure way, I would be happy. But for convenience sake I'm also fine if it's only stored on the phone as plain text (user don't *have to* store their credentials, jut the option to do so).

**Comment by ghost** [comment]
Hi,

Why you need to clear cookies always, it usseless as every website will make them again on your device.

About store your logins and password would be possible but it's even not secure as a cookies as other apps can access them on your device, second the login how Facebook use them are cookies so for now we dont have any way to change this.

**Comment by Adurol** [comment]
That storing the credentials on the phone in a not secure way enables other software to access this information is given. It is more a weighing between comfort and security: let users store the credentials in an insecure way (and inform them that this is the case) and get the comfort of not typing it in, or be on the safe side and type in the credentials on every login.

I'm sure with Qt5 there is a way to store such information in a more secure way then just plain text or in sqlite. I'm just not sure how much effort is needed to realize that and if it's worth it.

---

About the cookies: That was just an example. I'm not sure how Sailbook handles cookies itself. I assumed that it creates a new web instance on every start and on closing deletes all data (cookies, history, cache, etc.). Please correct me if I'm wrong. That cookies itself are needed to get Facebook working is clear. (With blocking of cookies Facebook would not work, but after closing "the site" [Sailbook] they are not needed anymore.)

**Comment by ghost** [comment]
Hi,

There is a always a way to do that, but it need to be support by Sailfish OS as the QTWebview is more then 5 years old and not up to date, and some things can not easy be done.

Second, Sailbook clears indeed always the chache etc, but not the the cookies that store the logins, but the first time you login with Sailbook Facebook as you to store them for one click login, if you there see NO then it dont store the logins and you need to login every time, you can also clear this login cookies into Sailbook, go to settings and choice there show Facebook logout buttom, when you do that you will see into the pullymenu Facebook logout buttom, after you logout everytime you need to put your logins stuff every time you startup Sailbook.
But you need to logout everytime also otherway it wont work.

**Comment by Adurol** [comment]
Oh, I didn't know that. I always used the logout-option and did logout, and didn't know that it is already solved via Cookies.
So I did login --> close Sailbook --> open Sailbook --> still logged in. That is exactly what I was looking for! (No need to login again.)

**Comment by ghost** [comment]
Ok happy it is solved for you ;)
