### ISSUE TITLE
Detect videos, full screen images, ... better

### ISSUE THREAD

**Issue by DylanVanAssche** [DylanVanAssche/harbour-sailbook#22]
Videos, full screen images are not detected 'well', we search for them every time we follow a link.
The biggest issue lies in the fact that if a Youtube video is embedded in the webpage we automatically are redirected to the video player but we can't see the actual page.

@codeandcreate 
@Sailbook 

Any idea's?

**Comment by codeandcreate** [comment]
Is it possible to select the embedded areas with document.querySelectorAll ?
If yes we can correct the dom so that we have a working <video> embed.
It would be even better if it is possible to hook up a regex while loading the html and replace the wrong dom before rendering.

**Comment by DylanVanAssche** [comment]
I don't know, something we need to figure out.
We can also detect the link and save it. If the user clicks on the player we push our VideoPlayerPage with the right link. The Facebook videos are handled like this already.

**Comment by DylanVanAssche** [comment]
@codeandcreate do you know Regex? I don't know it unfortunately...
However: https://stackoverflow.com/questions/9380062/is-using-a-regular-expression-faster-than-indexof#9380128
IndexOf seems to be a lot faster...
We should have one for Youtube videos, it should match the following url:

**goo.gl** YT videos
`https://lm.facebook.com/l.php?u=https%3A%2F%2Fgoo.gl%2FUgrzYF&h=ATMsmdJQtgb1cEE6xEQNXDcolRa12j5nQQFVJmInrr8teKLxM5TUrmxrmvnLlXWEw_AMgyg_SVkY201RcnrnEWOYWwtn9yXHJd9KYaT0XuoHZHiRyD67Jm9tEh7IjGSzwirvVHzq2HMFDO93FNl6q1Q&enc=AZNWRDl81OQPDGxKJHDt7gm_LdLNKPNXB8yxYA5ro3RAuPR7xggB6Ml2HnntbZM3DiG28LaeE3Z2ds0hl00ETX6tahFTD5Y179LvyF87cOhMVi69F98Cwodku0ULi-pq29NgoVhXzv3PgklG74OhWb6aBCgHT-pGV-0fXJ7gAdj2DZMklui5_8tAx7XZZHMgrdo&s=1`

_It's possible that other variants with youtube or something in the url are videos too but I can't find a real life example url. Those I scanned from the facebook mobile website are all like this._

**full screen FB photos (pages)**
`https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/12814536_954137744669216_802022625733356492_n.jpg?efg=eyJpIjoidCJ9&oh=f211043f9424b20970248c2c38d57110&oe=5A4FEC1D`

_Detecting 'fbcdn' might be enough in combination with the extension?_

**full screen FB photos (profiles)**
`https://m.facebook.com/photo/view_full_size/?fbid=1177745345668993&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13&ref=bookmarks`

_Checking for 'photo.php' and 'view_full_size'?_

**Comment by DylanVanAssche** [comment]
**goo.gl**
https://regex101.com/r/SqO7gQ/1

Result needs to be decoded and the full URL is available then.
Simple JS code:
```javascript
var myRegex = /lm\.facebook.com\/l\.php\?u=(.*)&h=/;
var url = myRegex.exec(decodeURIComponent(url))[1]; 
```

Thanks @codeandcreate
