### ISSUE TITLE
Scroll lagging

### ISSUE THREAD

**Issue by dizzi90** [DylanVanAssche/harbour-sailbook#68]
## Environment
Sailfish 2.1.3.5
Xperia X
```
uname -a
Linux Sailfish 3.10.84 #1 SMP PREEMPT Wed Oct 11 02:39:03 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

## Steps to reproduce
* Install.
```shell
curl https://openrepos.net/sites/default/files/packages/8135/harbour-sailbook-10.0-5.armv7hl.rpm -O
devel-su pkcon install-local ./harbour-sailbook-10.0-5.armv7hl.rpm
```
* Open Sailbook.
* Log in.
* Open feed.
* Scroll down.
* Outcome:
Either no response or slow response.

* Expected:
Scroll straight away.

**Comment by dizzi90** [comment]
Troubleshooting attempted:
https://openrepos.net/comment/21448#comment-21448

**Comment by DylanVanAssche** [comment]
Thanks for your report!
This is related to Sony Xperia X adaption, nothing I can fix at the moment in Sailbook itself, sorry.

**Comment by dizzi90** [comment]
In that case I can report it upstream. Thanks for the quick answer.
