### ISSUE TITLE
v10.1-release 4  not ship spanish translation any more

### ISSUE THREAD

**Issue by ghost** [DylanVanAssche/harbour-sailbook#78]

**Comment by DylanVanAssche** [comment]
Hmmm, Rudy did some clean up some time ago.. @Ruditimmermans

**Comment by ghost** [comment]
No as the Spanish guy dont update the language on Transiflex anymore even after sending some messages. Every translator for Sailbook translation should be use Transiflex.

**Comment by ghost** [comment]
One more time wasted my time with you @Ruditimmermans .
 So I hope that @carmenfdezb take care this.

**Comment by ghost** [comment]
Fixed on SB -v 10.1.5 ,Spanish is Spanish not matter what country is coming.  : |
