### ISSUE TITLE
Location verification

### ISSUE THREAD

**Issue by marxistvegan** [DylanVanAssche/harbour-sailbook#85]
**What happens**: 
New facebook policy requires location to of accounts managing a page. Everytime I log in to publish on said page I am told I need to reverify my account. There is only one way to do this, which is to use the Android/iOS facebook app to verify. 
 
**Environment**: 
    - Sailfish OS version: 2.2.1 and also the previous
    - Sailfish OS hardware: Xperia X

**Suggestion**
See if there is a way to pull the location request feature that exists in the android app to work in Sailbook. I know this might be asking a lot but at the moment I need to run the android facebook app which drains the battery and stays running even when told not to.

**Comment by DylanVanAssche** [comment]
Hmmm... This requires GPS location requests in QtWebkit.
Does it work properly in Webcat?

**Comment by marxistvegan** [comment]
I have not tried, and so far the facebook site literally says it can only be done in the Android or iOS application and not via the web site. Which I have sent complaints to them that this is both unfair to those that do not have mobile devices and also is in general a bad approach.

**Comment by DylanVanAssche** [comment]
Sailbook is a webview application, native stuff isn't supported due the nature of Facebook. I'm sorry!
If it becomes possible in the webapp then it's might be possible in Sailbook too, but at the moment it won't work then.

I will close this issue if you don't mind since it's related to Facebook itself.
