### ISSUE TITLE
improve performances (if possible)

### ISSUE THREAD

**Issue by legacychimera247** [DylanVanAssche/harbour-sailbook#86]
i noticed that if you scrool long on a page (sometimes even just two weeks) performances are really bad with sailbook taking ages to just load a post and even more ages if a picture is included.

is this something that could be improved or it's just a webview fault?

**Comment by DylanVanAssche** [comment]
It's the Webview itself. QtWebEngine from SFOS 3.0 might fix this

**Comment by legacychimera247** [comment]
ok, we can close this one then
